server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloud_guigu?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: spf.2020
  jackson:
    default-property-inclusion: non_null   # 设置返回json结果中的null值不显示

mybatis:
  mapper-locations: classpath*:/com/tengol/springcloud/guigu/mapper/*Mapper.xml
  type-aliases-package: com.tengol.springcloud.guigu.entity
  configuration:
    use-actual-param-name: true
    map-underscore-to-camel-case: true

